version: '3.1'

services:

  nginx:
    container_name: new_container-nginx
    build:
      context: .docker/config/nginx
    ports:
      - 8000:80
    working_dir: /application
    volumes:
      - .:/application
      - .docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: new_container-php
    build:
      context: .docker/config/php
    ports:
      - 9000:9000
    working_dir: /application
    volumes:
      - .:/application
      - .docker/config/php/php.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini # PHP FPM
      - .docker/config/php/php.ini:/usr/local/etc/php/conf.d/docker-php-zzz-overrides.ini # PHP Client

  mariadb:
    container_name: new_cotainner-mariadb
    build:
      context: .docker/config/mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=blog2best
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    working_dir: /application
    volumes:
      - .:/application
